<a href="https://colab.research.google.com/github/iAmirHosein92/Class_Exercise_Solution/blob/main/HousePricePredict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

In [112]:

df = pd.read_csv('housedata.csv')
for i in range(1, 23):
  try:
    housedf = pd.read_csv(f'l{i} - housedataset.csv', header=None)
    housedf.columns = df.columns
    df = pd.concat([df, housedf], ignore_index=True)
  except:
    continue

In [113]:
df.sample(5)

,h_type,date,adress,loc,num_floor,unit_per_floor,price,age,statuse,view,...,parking,warehouse,balcony,equipment,nearby,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
8120,آپارتمان,1404/02/08,مفتح شمالی بالاتر از بهارشیراز,22,3,1,"9,800,000,000 تومان",24,تخلیه,سنگ,...,0,1,1,کولر_پکیج_گاز,24,تخلیه,سنگ,شخصي,NaN,NaN
1445,آپارتمان,1404/01/17,الهیه بالاتراز خزر,1,7,1,"112,000,000,000 تومان",15,مسکونی,سنگ,...,1,1,1,شوفاژ_کولر_آسانسور_گاز,15,مسکونی,سنگ,شخصي,NaN,NaN
3393,آپارتمان,1404/02/02,استاد معین ك نظری ك قربانی پ 15,9,2,1,"3,000,000,000 تومان",30,تخلیه,سنگ,...,0,0,0,کولر_گاز,30,تخلیه,سنگ,شخصي,NaN,NaN
998,آپارتمان,1404/01/26,قیطریه چیذر,1,4,1,"9,570,000,000 تومان",20,اجاره,سنگ,...,0,1,0,شوفاژ_کولر,20,اجاره,سنگ,شخصي,NaN,NaN
1863,آپارتمان,1404/01/24,دروس قبا نرسیده به ك آذر,3,3,2,"22,000,000,000 تومان",490,20,تخلیه,...,1,1,1,شوفاژ_کولر_گاز,490,20,تخلیه,سنگ,شخصي,NaN

In [114]:
df= df.drop_duplicates(subset=['adress'])

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2398 entries, 0 to 8208
Data columns (total 33 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   h_type          2398 non-null   object
 1   date            2398 non-null   object
 2   adress          2398 non-null   object
 3   loc             2398 non-null   int64
 4   num_floor       2398 non-null   int64
 5   unit_per_floor  2398 non-null   object
 6   price           2398 non-null   object
 7   age             2398 non-null   object
 8   statuse         2398 non-null   object
 9   view            2398 non-null   object
 10  doc_status      2397 non-null   object
 11  north           2398 non-null   int64
 12  sought          2398 non-null   int64
 13  west            2398 non-null   int64
 14  east            2398 non-null   int64
 15  floor           2398 non-null   object
 16  area            2398 non-null   int64
 17  num_sleep       2398 non-null   int64
 18  tel             2392 non-null   object
 19  kitch           2398 non-null   object
 20  service         2398 non-null   object
 21  floor_covering  2398 non-null   object
 22  open            2398 non-null   int64
 23  parking         2398 non-null   int64
 24  warehouse       2398 non-null   int64
 25  balcony         2398 non-null   int64
 26  equipment       2390 non-null   object
 27  nearby          2398 non-null   object
 28  Unnamed: 28     2398 non-null   object
 29  Unnamed: 29     2398 non-null   object
 30  Unnamed: 30     2393 non-null   object
 31  Unnamed: 31     85 non-null     object
 32  Unnamed: 32     16 non-null     object
dtypes: int64(12), object(21)
memory usage: 637.0+ KB

In [116]:
df = df.drop(columns=['tel', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32'])

In [117]:
df = df.dropna()

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2389 entries, 0 to 8208
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   h_type          2389 non-null   object
 1   date            2389 non-null   object
 2   adress          2389 non-null   object
 3   loc             2389 non-null   int64
 4   num_floor       2389 non-null   int64
 5   unit_per_floor  2389 non-null   object
 6   price           2389 non-null   object
 7   age             2389 non-null   object
 8   statuse         2389 non-null   object
 9   view            2389 non-null   object
 10  doc_status      2389 non-null   object
 11  north           2389 non-null   int64
 12  sought          2389 non-null   int64
 13  west            2389 non-null   int64
 14  east            2389 non-null   int64
 15  floor           2389 non-null   object
 16  area            2389 non-null   int64
 17  num_sleep       2389 non-null   int64
 18  kitch           2389 non-null   object
 19  service         2389 non-null   object
 20  floor_covering  2389 non-null   object
 21  open            2389 non-null   int64
 22  parking         2389 non-null   int64
 23  warehouse       2389 non-null   int64
 24  balcony         2389 non-null   int64
 25  equipment       2389 non-null   object
 26  nearby          2389 non-null   object
dtypes: int64(12), object(15)
memory usage: 522.6+ KB

In [119]:
df.isna().sum()

h_type            0
date              0
adress            0
loc               0
num_floor         0
unit_per_floor    0
price             0
age               0
statuse           0
view              0
doc_status        0
north             0
sought            0
west              0
east              0
floor             0
area              0
num_sleep         0
kitch             0
service           0
floor_covering    0
open              0
parking           0
warehouse         0
balcony           0
equipment         0
nearby            0
dtype: int64

In [120]:
df['price'] = df['price'].str.replace(',', '')
df['price'] = df['price'].str.replace('تومان', '')
df['price'] = df['price'].astype(int)

In [121]:
df.describe()

,loc,num_floor,price,north,sought,west,east,area,num_sleep,open,parking,warehouse,balcony
count,2389.000000,2389.000000,2.389000e+03,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000
mean,7.164923,5.464211,1.821818e+10,0.490582,0.554625,0.043114,0.039347,113.186270,2.172039,0.933864,0.692758,0.858937,0.620343
std,6.690609,3.845106,3.332143e+10,0.500016,0.497111,0.203157,0.194460,108.164812,1.457995,0.248573,0.461447,0.348160,0.485403
min,1.000000,1.000000,1.250000e+09,0.000000,0.000000,0.000000,0.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,4.000000,6.000000e+09,0.000000,0.000000,0.000000,0.000000,70.000000,2.000000,1.000000,0.000000,1.000000,0.000000
50%,4.000000,5.000000,1.078000e+10,0.000000,1.000000,0.000000,0.000000,98.000000,2.000000,1.000000,1.000000,1.000000,1.000000
75%,9.000000,5.000000,2.020000e+10,1.000000,1.000000,0.000000,0.000000,135.000000,3.000000,1.000000,1.000000,1.000000,1.000000
max,22.000000,32.000000,8.000000e+11,1.000000,1.000000,1.000000,1.000000,3200.000000,40.000000,1.000000,1.000000,1.000000,1.000000

In [83]:
df['price']

0       14000000000
1        4500000000
2       10500000000
3       18000000000
4        5000000000
           ...
8181    12300000000
8190    14000000000
8199     9800000000
8201     9500000000
8208    15300000000
Name: price, Length: 2389, dtype: int64

In [122]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [141]:
df.floor.unique()

array([ 3,  1,  5,  4,  2,  7, 10,  0, -1,  8,  6, 11,  9, 34, 14, 22, 13,
       -3, 12, 15, 25, 28, 17, 23, 16, 20, 19, 18])

In [135]:
df['age'] = df['age'].replace(['نوساز', 'مسکونی'], 0)
df['nearby'] = df['age'].replace(['نوساز', 'مسکونی'], 0)

In [140]:
import re

def extract_floor(value):
    value = str(value).strip()

    numbers = re.findall(r'-?\d+', value)

    if numbers:
        return int(max(map(int, numbers)))
    else:
        return 0


df['floor'] = df['floor'].apply(extract_floor)

In [137]:
convert_dict = {'nearby' : int, 'age': int}
df.astype(convert_dict)

,h_type,date,adress,loc,num_floor,unit_per_floor,price,age,statuse,view,...,num_sleep,kitch,service,floor_covering,open,parking,warehouse,balcony,equipment,nearby
0,آپارتمان,1404/01/28,تهرانپارس خ 188غربی,4,5,2,14000000000,15,مسکونی,سنگ,...,2,MDF,ايراني فرنگي,سنگ,1,1,1,1,شوفاژ_کولر_آسانسور_گاز,15
1,آپارتمان,1404/01/26,تهرانپارس بلوار پروین خ 196 شرقی,4,4,1,4500000000,1,تخلیه,سنگ,...,2,MDF,ايراني فرنگي,سراميک,1,0,1,1,پکیج,1
2,آپارتمان,1404/01/26,فرجام غربی خ حیدرخانی,4,5,1,10500000000,4,تخلیه,سنگ,...,2,MDF,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_پکیج,4
3,آپارتمان,1404/01/31,هروی گلستان,4,5,2,18000000000,17,مسکونی,سنگ,...,2,MDF,ايراني فرنگي,سراميک,1,1,1,0,شوفاژ_کولر_آسانسور,17
4,آپارتمان,1404/01/26,هنگام چهارراه استقلال,4,4,2,5000000000,17,مسکونی,سنگ,...,1,MDF,ايراني فرنگي,سراميک,0,1,1,0,کولر_گاز,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8181,آپارتمان,1404/02/03,شهرك راه آهن شهرك كوهستان,22,8,4,12300000000,16,مسکونی,سنگ,...,3,هایگلاس,ايرانی,پارکت,1,1,0,1,شوفاژ_کولر_آسانسور_گاز,16
8190,آپارتمان,1404/02/01,شهرك راه آهن میدان موج,22,15,5,14000000000,4,مسکونی,ترکیبی,...,2,هایگلاس,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_گاز,4
8199,آپارتمان,1404/02/09,شهرك راه آهن بین رزمال و بیمارستان تریتا,22,25,8,9800000000,3,مسکونی,ترکیبی,...,2,MDF,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_گاز,3
8201,آپارتمان,1404/02/08,شهرك راه آهن خ دریاچه,22,20,4,9500000000,6,مسکونی,سنگ,...,3,MDF,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_گاز,6
8208,آپارتمان,1404/02/06,چیتگر میدان ساحل,22,30,8,15300000000,5,تخلیه,ترکیبی,...,2,هایگلاس,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_گاز,5

In [149]:
numerical_cols = df.select_dtypes(include=['number']).columns
categorical_cols = df.select_dtypes(exclude=['number']).columns
print("Numerical Columns:", numerical_cols.tolist())
print("Categorical Columns:", categorical_cols.tolist())

print("\nNumerical Columns:")
display(df[numerical_cols].describe())

Numerical Columns: ['loc', 'num_floor', 'price', 'north', 'sought', 'west', 'east', 'floor', 'area', 'num_sleep', 'open', 'parking', 'warehouse', 'balcony']
Categorical Columns: ['h_type', 'adress', 'unit_per_floor', 'age', 'statuse', 'view', 'doc_status', 'kitch', 'service', 'floor_covering', 'equipment', 'nearby']

Numerical Columns:

,loc,num_floor,price,north,sought,west,east,floor,area,num_sleep,open,parking,warehouse,balcony
count,2389.000000,2389.000000,2.389000e+03,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000,2389.000000
mean,7.164923,5.464211,1.821818e+10,0.490582,0.554625,0.043114,0.039347,2.990373,113.186270,2.172039,0.933864,0.692758,0.858937,0.620343
std,6.690609,3.845106,3.332143e+10,0.500016,0.497111,0.203157,0.194460,2.680251,108.164812,1.457995,0.248573,0.461447,0.348160,0.485403
min,1.000000,1.000000,1.250000e+09,0.000000,0.000000,0.000000,0.000000,-3.000000,30.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,4.000000,6.000000e+09,0.000000,0.000000,0.000000,0.000000,1.000000,70.000000,2.000000,1.000000,0.000000,1.000000,0.000000
50%,4.000000,5.000000,1.078000e+10,0.000000,1.000000,0.000000,0.000000,3.000000,98.000000,2.000000,1.000000,1.000000,1.000000,1.000000
75%,9.000000,5.000000,2.020000e+10,1.000000,1.000000,0.000000,0.000000,4.000000,135.000000,3.000000,1.000000,1.000000,1.000000,1.000000
max,22.000000,32.000000,8.000000e+11,1.000000,1.000000,1.000000,1.000000,34.000000,3200.000000,40.000000,1.000000,1.000000,1.000000,1.000000

In [143]:
df.drop(columns=['date'], inplace=True)

In [146]:
df.sample(5)

,h_type,adress,loc,num_floor,unit_per_floor,price,age,statuse,view,doc_status,...,num_sleep,kitch,service,floor_covering,open,parking,warehouse,balcony,equipment,nearby
4225,آپارتمان,آزادی خ طوس ك مبارز بن بست بروجردی پلاك 8,10,4,2,4100000000,8,مسکونی,سنگ,شخصي,...,1,نا مشخص,ايرانی,سراميک,1,0,0,0,کولر_آسانسور_گاز,8
1471,آپارتمان,اوین خ احمد پور خ مفیدی,1,5,3,24800000000,8,تخلیه,سنگ,شخصي,...,3,MDF,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_چیلر_گاز,8
317,آپارتمان,تهران پارس فلكه 1 خ 152,4,6,2,21080000000,0,تخلیه,سنگ,شخصي,...,2,چوبي,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_پکیج_گاز,0
889,آپارتمان,سراج روبروی بانك تجارت,4,5,4,6700000000,8,مسکونی,سنگ,شخصي,...,2,MDF,ايراني فرنگي,سراميک,1,1,1,1,کولر_آسانسور_پکیج_گاز,8
73,آپارتمان,جشنواره خ امین ك علامه طباطبایی,4,4,1,3800000000,12,مسکونی,سنگ,شخصي,...,1,MDF,ايرانی,سراميک,1,0,1,0,شوفاژ_کولر_آسانسور_گاز,12

In [10]:
for col in ['parking', 'warehouse', 'balcony']:
    df[col] = df[col].astype(str).str.strip()
    df[col] = df[col].apply(lambda x: 1 if x in ['دارد', 'بله', '1', 'True', 'true', 'بله‌'] else 0)

In [11]:
df.sample(2)

,h_type,adress,loc,num_floor,unit_per_floor,price,age,statuse,view,doc_status,...,open,parking,warehouse,balcony,equipment,nearby,area_rooms,area_age,area_squared,age_squared
1675,آپارتمان,میدان امام حسین خ اقبال,7,0.064516,0.00,0.000000,0.566667,تخلیه,سنگ,شخصي,...,1,0,0,1,شوفاژ_کولر,0.00425,0.005682,0.128788,0.000000,0.321111
858,آپارتمان,دارآباد نرسیده به خ پورابتهاج,1,0.161290,0.05,0.281211,0.000000,تخلیه,سنگ,شخصي,...,1,1,1,1,آسانسور_پکیج,0.00000,0.023409,0.000000,0.176667,0.000000

In [35]:
feature = df.drop(columns=['price', 'h_type', 'adress'])
target = df['price']

In [30]:
df.h_type.unique()

array(['آپارتمان'], dtype=object)

In [41]:
categorical_features = feature.select_dtypes(include=['object']).columns
numerical_features = feature.select_dtypes(include=['number']).columns
print(categorical_features)
print(numerical_features)

Index(['statuse', 'view', 'doc_status', 'kitch', 'service', 'floor_covering',
       'equipment'],
      dtype='object')
Index(['loc', 'num_floor', 'unit_per_floor', 'age', 'north', 'sought', 'west',
       'east', 'floor', 'area', 'num_sleep', 'open', 'parking', 'warehouse',
       'balcony', 'nearby', 'area_rooms', 'area_age', 'area_squared',
       'age_squared'],
      dtype='object')

In [47]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, OneHotEncoder

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
])

pca = PCA(n_components=5)
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
 ('pca', pca)])

X_transformed = pipeline.fit_transform(feature)

print( preprocessor.fit_transform(feature).shape)
print( X_transformed.shape)

(2389, 259)
(2389, 5)

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature, target, random_state=42, test_size=0.3)

In [49]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), SVR(), KNeighborsRegressor()]
models_name = ['LinearRegression', 'DecisionTreeRegressor', 'RandomForestRegressor', 'SVR', 'KNeighborsRegressor']
for model, name in zip(models, models_name):
    clf = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('pca', pca),
        ('classifier', model)
    ])

    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} MSE: {mse:.2f}, MAE: {mae:.2f}, R2: {r2:.2f}")

LinearRegression MSE: 0.02, MAE: 0.10, R2: 0.65
DecisionTreeRegressor MSE: 0.03, MAE: 0.11, R2: 0.52
RandomForestRegressor MSE: 0.01, MAE: 0.08, R2: 0.78
SVR MSE: 0.02, MAE: 0.09, R2: 0.77
KNeighborsRegressor MSE: 0.02, MAE: 0.08, R2: 0.77

# ***Without PCA:***

In [65]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

models = [LinearRegression(), DecisionTreeRegressor(), RandomForestRegressor(), SVR(), KNeighborsRegressor()]
models_name = ['LinearRegression', 'DecisionTreeRegressor', 'RandomForestRegressor', 'SVR', 'KNeighborsRegressor']
for model, name in zip(models, models_name):
    clf = Pipeline(steps=[
        ('preprocessor', preprocessor),

        ('classifier', model)
    ])

    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    print(f"{name} MSE: {mse:.2f}, MAE: {mae:.2f}, R2: {r2:.2f}")
    #Get important featurs
    if name == 'RandomForestRegressor':
        importances = model.feature_importances_
        sorted_idx = np.argsort(importances)[::-1][:10]
        print(f"Top 10 important features for {name}:")
        for idx in sorted_idx:
            print(f"{feature.columns[idx]}: {importances[idx]}")

LinearRegression MSE: 0.01, MAE: 0.08, R2: 0.78
DecisionTreeRegressor MSE: 0.02, MAE: 0.07, R2: 0.78
RandomForestRegressor MSE: 0.01, MAE: 0.06, R2: 0.87
Top 10 important features for RandomForestRegressor:
west: 0.3410051608768591
parking: 0.3337973363917192
loc: 0.1379411732833812
floor_covering: 0.051150974241251236
open: 0.015299225776899959
service: 0.012163653645199134
sought: 0.010562844138188896
num_floor: 0.010178080120494282
warehouse: 0.008124565141621196
age: 0.006747984556196834
SVR MSE: 0.01, MAE: 0.08, R2: 0.82
KNeighborsRegressor MSE: 0.02, MAE: 0.09, R2: 0.74

***Random Forest Worked Better With R2:0.87***

In [68]:
from xgboost import XGBRegressor

clf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBRegressor(n_estimators=200, learning_rate=0.1, random_state=42))
])

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"XGBRegressor MSE: {mse:.2f}, MAE: {mae:.2f}, R2: {r2:.2f}")

XGBRegressor MSE: 0.01, MAE: 0.06, R2: 0.87